# Generated by Django 5.0.7 on 2024-07-30 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_books',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='bookstore/images'),
        ),
    ]
