# Generated by Django 5.0.7 on 2024-07-31 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authers', '0001_initial'),
        ('bookstore', '0003_alter_all_books_auther'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_books',
            name='auther',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookstore', to='authers.auther'),
        ),
    ]
